### ISSUE TITLE
watsonsdk.aar.zip download link is behind IBM firewall

### ISSUE THREAD

**Issue by nfriedly** [watson-developer-cloud/speech-android-sdk#1]
The link points to https://git.hursley.ibm.com/w3bluemix/WatsonAndroidSpeechSDK/blob/master/speech-android-wrapper/build/outputs/aar/watsonsdk.aar.zip - we should probably put a copy of it in github releases.

**Comment by daniel-bolanos** [comment]
thanks Nathan
