### ISSUE TITLE
Websocket ssl error 

### ISSUE THREAD

**Issue by abhiguru** [watson-developer-cloud/speech-android-sdk#11]
I followed the instructions in the quick start guide but was unable to run the example I get the error below: 

com.ibm.watson.developer_cloud.android.examples E: WebSocket error
com.ibm.watson.developer_cloud.android.examples E: ssl == null
com.ibm.watson.developer_cloud.android.examples E: ssl == null

I read here https://developer.ibm.com/answers/questions/174846/using-websockets-in-speech-to-text.html that there needs to be a cert installed for wss but I could not find instructions related to it can you point me to where the instructions are ?

**Comment by KeyOnTech** [comment]
Im sure you did but checking did you add the internet permission to your manifest

<uses-permission android:name="android.permission.INTERNET" />

**Comment by abhiguru** [comment]
I did(below manifest), btw thanks for the write-up was helpful!  
uses-permission android:name="android.permission.RECORD_AUDIO"uses-permission android:name="android.permission.INTERNET" uses-permission android:name="android.permission.WRITE_SETTINGS" uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"

**Comment by mihui** [comment]
@abhiguru could this one be closed?
