### ISSUE TITLE
No watsonsdk.aar

### ISSUE THREAD

**Issue by KlasZetterlund** [watson-developer-cloud/speech-android-sdk#12]
This might be a dumb question but I'm totally stuck on step two of installation.
1. Download the speech-android-wrapper.aar
2. Once unzipped drag the watsonsdk.aar file into your Android Studio project view under the libs folder.

I download the speech-amdroid-wrapper.aar and there is no watsonsdk.aar inside of it. Where do I get the watsonsdk.aar?

Kind regards

**Comment by nfriedly** [comment]
I think it should say "Once unzipped, drag the _speech-android-wrapper.aar_ file into your Android Studio project view under the libs folder."

@germanattanasio ?

**Comment by germanattanasio** [comment]
yeah
