### ISSUE TITLE
SpeechRecorderDelegate documentation or souce code

### ISSUE THREAD

**Issue by blob42** [watson-developer-cloud/speech-android-sdk#17]
Hi,

The readme states that it is possible to process or use the audio that is recorded using _SpeechRecorderDelegate_ and _setRecorderDelegate_. where is the API reference for this delegate.

How can I use the audio stream/file that is streamed ?

Thx

**Comment by germanattanasio** [comment]
hey, @sp4ke try to use the android-SDK. This project will be deprecated as it only supports the speech services.

**Comment by blob42** [comment]
Hi @germanattanasio , thanks for the information.
