### ISSUE TITLE
Deprecate speech-android-sdk

### ISSUE THREAD

**Issue by Hsaylor** [watson-developer-cloud/speech-android-sdk#18]
@germanattanasio 

With the shift to making the java-sdk more consumable on Android, we are deprecating this sdk. The only thing this sdk provides that is not already provided by the java-sdk is the ability to explicitly end audio transcription. So, in order to deprecate this sdk, we need to provide that functionality within the java-sdk.
- [x] Provide a function to explicitly end transcription within the java-sdk
- [ ] Add OPUS encoding as an option within the android-sdk

**Comment by daniel-bolanos** [comment]
Hello @Hsaylor,

Before deprecating it please lets make sure these angles are covered:

does the java-sdk provide live microphone capture?
does it include a sample android app showcasing the SDK to perform live audio capture?
does the java-sdk allow stream based opus encoding so we can feed a compressed stream of audio to STT?

Dani

**Comment by Hsaylor** [comment]
Hey @daniel-bolanos, 

The companion sdk to the java-sdk, the [android-sdk](https://github.com/watson-developer-cloud/android-sdk), provides utility for live microphone capture, as well as an app showcasing it.

I do believe the java-sdk supports stream-based opus encoding, since it asks for a generic `InputSteam` and the service endpoints are still those of the Watson Speech To Text service. 
However, I do not believe that the convenience method for microphone capture within the android-sdk currently has the option to compress to opus format. I can add that to our roadmap if it's something this sdk supports.

**Comment by daniel-bolanos** [comment]
Hi @Hsaylor, thanks for the detailed answer, I just took a look at the android-sdk repo and saw how the code from the original speech-android-sdk was refactored and added there.

For mobile platforms, in this case android, it is key that we can produce a stream of audio in opus format that we can feed to the STT service. Sending uncompressed audio is too heavy. Please lets make sure opus encoding is working for live interaction with STT.

For mobile I believe the live usecase is the most important one, and for that we need: websockets+live_capture_from_mic+opus, when the java-sdk + android-sdk have that, then we will be good to go. 

Dani

**Comment by Hsaylor** [comment]
I absolutely agree that uncompressed audio is too heavy for any real use case. I'll talk a look at this sdk and make sure opus encoding works with the android-sdk

**Comment by daniel-bolanos** [comment]
Thank you @Hsaylor!
