### ISSUE TITLE
stop currently playing audio of Text-to-Speech

### ISSUE THREAD

**Issue by mitulgolakiya** [watson-developer-cloud/speech-android-sdk#23]
Hi,

We are using IBM Watson in our production build. We have a Siri kind of functionality for our app.

We were looking for if there is any way by which we can stop the audio that is currently played by Text to Speech service ?

**Comment by mihui** [comment]
There is a private method called "private void stopTtsPlayer()" in TTSUtility class, it can stop it.

I am working on refactoring, so I merged it into TextToSpeech class and opened this method public called "public void stopAudio()"

See this change: https://github.com/watson-developer-cloud/speech-android-sdk/commit/1f9dfb162affb0e2800b013a30095fed577d0f61

**Comment by mitulgolakiya** [comment]
Thanks, @mihui.

so how soon this will be released ?

**Comment by mihui** [comment]
@mitulgolakiya as long as the new PR is merged, this could be resolved.
