### ISSUE TITLE
android.media.AudioTrack: getMinBufferSize(): 1948401012 Hz is not a supported sample rate.

### ISSUE THREAD

**Issue by YoungCholKim** [watson-developer-cloud/speech-android-sdk#25]
Hi. I've got this error when call synthesize method.

I found someone in IBMDeveloper site got the same error but no solution yet.
https://developer.ibm.com/answers/questions/230127/android-text-to-speech-returns-2-buffer-size.html

LOGCAT :

> 07-08 21:33:04.060 28864-28864/ D/TextToSpeech: synthesize called: https://stream.watsonplatform.net/text-to-speech/api/v1/synthesize
> 07-08 21:33:04.060 28864-28864/ I/com.ibm.watson.developer_cloud.android.text_to_speech.v1.TTSUtility: Start requesting TTS... (audio/wav)
> 07-08 21:33:04.070 28864-29059/ D/com.ibm.watson.developer_cloud.android.text_to_speech.v1.TTSUtility: using basic authentication
> 07-08 21:33:06.280 28864-29059/ E/android.media.AudioTrack: getMinBufferSize(): 1948401012 Hz is not a supported sample rate.
> 07-08 21:33:06.280 28864-29059/ W/System.err: java.lang.IllegalArgumentException: 1948401012Hz is not a supported sample rate.
> 07-08 21:33:06.290 28864-29059/ W/System.err:     at android.media.AudioTrack.audioParamCheck(AudioTrack.java:380)
> 07-08 21:33:06.290 28864-29059/ W/System.err:     at android.media.AudioTrack.<init>(AudioTrack.java:315)
> 07-08 21:33:06.290 28864-29059/ W/System.err:     at android.media.AudioTrack.<init>(AudioTrack.java:265)
> 07-08 21:33:06.290 28864-29059/ W/System.err:     at com.ibm.watson.developer_cloud.android.text_to_speech.v1.TTSUtility.initPlayer(TTSUtility.java:129)
> 07-08 21:33:06.300 28864-29059/ W/System.err:     at com.ibm.watson.developer_cloud.android.text_to_speech.v1.TTSUtility.access$800(TTSUtility.java:52)
> 07-08 21:33:06.300 28864-29059/ W/System.err:     at com.ibm.watson.developer_cloud.android.text_to_speech.v1.TTSUtility$TTSThread.run(TTSUtility.java:220)
> 07-08 21:33:06.300 28864-29059/ I/com.ibm.watson.developer_cloud.android.text_to_speech.v1.TTSUtility: Stopping audioTrack...

Codes:

```
protected void procTTS(View view) throws JSONException {
        textAnswer = (TextView) findViewById(R.id.txtAnswer);
        String ttsText=textAnswer.getText().toString();
        TextToSpeech.sharedInstance().synthesize(ttsText);
    }
private boolean initTTS() {
        String username = getString(R.string.TTSUsername);
        String password = getString(R.string.TTSPassword);
        String serviceURL = "https://stream.watsonplatform.net/text-to-speech/api";
        TextToSpeech.sharedInstance().initWithContext(getHost(serviceURL));
        TextToSpeech.sharedInstance().setCredentials(username, password);
        TextToSpeech.sharedInstance().setVoice(getString(R.string.voiceDefault));
        return true;
    }
```

**Comment by germanattanasio** [comment]
How large is the text you are trying to synthesize? I think this just happens if you synthesize a large text.

**Comment by YoungCholKim** [comment]
Just one sentence or few words that I tried.

**Comment by TThana** [comment]
Got this error too.
Just synthesize("Hello");

**Comment by ylassoued** [comment]
Any luck with this? I am experiencing the same problem with text to speech in one of my projects. The example application provided as part of the Android Speech SDK works fine. However, when I copy paste the same code under my project, it does not work. I even started a new project from scratch, using the same target and min SDK versions as in the Android Speech SDK example app. But that does not work either. I am running the code on a Nexus 6 emulator, with very short text messages.
I have noticed that using the  Android Speech SDK example app, AudioTrack is instantiated by TTSUtility with the following parameters: new AudioTrack(3, 22050, 4, 2, 2064, 1). However, from my code it is bing instantiated with: new AudioTrack(3, 1948401012, 4, 2, -2, 1).
Any idea?

**Comment by nacho4d** [comment]
> I even started a new project from scratch, using the same target and min SDK versions as in the Android Speech SDK example app. But that does not work either.

@ylassoued Can you share this sample app?

**Comment by ylassoued** [comment]
Problem solved. This is was an error on my side... Somehow my credentials which are specified in a config file got messed up. As error messages from the Watson TTS service are not dealt with by the Speech Android API, TTSUtility was attempting to read the server response (error message) as WAV data... I figured this out after I used the latest Watson Java SDK 3.4.0, which threw an exception upon the authentication failure...

**Comment by nacho4d** [comment]
Glad to know!

I have experienced weird issues somewhere else and then realized credentials were incorrect..  😢

**Comment by ihuman15** [comment]
Hi Guys, I am also getting the same exception while trying for Text-to-Speech.
Below is the log:

`D/OkHttp: --> POST https://stream.watsonplatform.net/text-to-speech/api/v1/synthesize?voice=en-US_MichaelVoice http/1.1 (13-byte body)
`
`
D/OkHttp: <-- 200 OK https://stream.watsonplatform.net/text-to-speech/api/v1/synthesize?voice=en-US_MichaelVoice (417ms, unknown-length body)
`
`
E/android.media.AudioTrack: getMinBufferSize(): 1987804923 Hz is not a supported sample rate.
`

I am using the service credentials for the Text-to-Speech API as given on the `bluemix` site.
![watson](https://user-images.githubusercontent.com/19462019/42494561-454f7850-843e-11e8-9b0d-487f6bdd4c64.png)

Can anyone suggest where am I going wrong? I am using the Android SDK along with the Java SDK.
