### ISSUE TITLE
com-sun-jna-android-arm-libjnidispatch-so-not-found-in-resource-path

### ISSUE THREAD

**Issue by efoertsch** [watson-developer-cloud/speech-android-sdk#28]
Here is link to my original post on this problem in SO.

[http://stackoverflow.com/questions/37621358/com-sun-jna-android-arm-libjnidispatch-so-not-found-in-resource-path](http://stackoverflow.com/questions/37621358/com-sun-jna-android-arm-libjnidispatch-so-not-found-in-resource-path)

Still looking for a fix or workaround.

**Comment by mihui** [comment]
I've been working for this issue for a while, but unfortunately I can't reproduce your issues, would it be possible for you to share the a simple project with that issue? (inculding the configurations of the multidexing and dependencies) Maybe this way I can do some investigations base on it.

**Comment by mihui** [comment]
@efoertsch Looking forward to your reply, thanks.

**Comment by efoertsch** [comment]
MIchael -

Sorry - Was out on vacation. I had created a simple app and it worked fine.
When I tried to incorporate it into a much larger app which uses
multidexing (not sure if that is the issue or not) it gives the error.
Using 'Native Libs Monitor' app I was able to see that  libjnidispatch.so
was part of app package. So not sure why it isn't being found. I don't have
C/C++ experience to root around further.

**Comment by mihui** [comment]
Hey Eric, 

so my question was is it possible to share a sample project with multidexing, I'm not saying your real project, but a project to reproduce the issue with larger size? Thanks.

**Comment by efoertsch** [comment]
Michael - To be honest I don't have time to create a sample project with
enough methods to make a multidex app.

**Comment by mihui** [comment]
Hi Eric, 

understood.
