### ISSUE TITLE
Provide a sample implementation that extends Android's RecognitionService

### ISSUE THREAD

**Issue by Kaljurand** [watson-developer-cloud/speech-android-sdk#5]
Provide a sample implementation that extends Android's RecognitionService (see: https://developer.android.com/reference/android/speech/RecognitionService.html) in order to reduce the integration effort for apps that already interact with a recognition service by calling `SpeechRecognizer.createSpeechRecognizer` (https://developer.android.com/reference/android/speech/SpeechRecognizer.html)

**Comment by daniel-bolanos** [comment]
Hello @Kaljurand , this is a good idea. We will try to find some time to implement this... thank you for the feedback.
