### ISSUE TITLE
speech-android-sdk and Bluemix

### ISSUE THREAD

**Issue by satlandau** [watson-developer-cloud/speech-android-sdk#6]
Hi Daniel,
We're getting the attached authentication error message. 
Any Idea how to solve it?

![authenticationerror](https://cloud.githubusercontent.com/assets/13630961/12040262/3a991ce6-ae70-11e5-92ec-77d9d6196f2c.jpg)

Thanks,
Gil

**Comment by germanattanasio** [comment]
Please don't post images with credentials

**Comment by daniel-bolanos** [comment]
Hello @satlandau , did you solve your problem? You just need to put your credentials in the code...

please let me know

Dani
