### ISSUE TITLE
how do i get user credentials 

### ISSUE THREAD

**Issue by rakshitsoni02** [watson-developer-cloud/speech-android-sdk#8]

**Comment by nfriedly** [comment]
Hi @rakshitsoni02, sorry about that, we have a page with instructions for that at http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/getting_started/gs-credentials.shtml since it applies to all SDKs, however it should have been linked to from the readme. I've fixed it now.

**Comment by rakshitsoni02** [comment]
ok thanks
